### ISSUE TITLE
missing proxy-mirror.key

### ISSUE THREAD

**Issue by DavideMontersino** [miensol/proxy-mirror#2]
I updated this repo to be able to start it (some dependencies do not exist anymore)

..however, when I try ti start it with

```sh
    node index.js
```

I get the following:

```
Error: ENOENT: no such file or directory, open '/home/davide/Projects/proxy-mirror/cert/proxy-mirror.key'
```

**Comment by miensol** [comment]
You can use `setup-certificate.sh` to generate a certificate key pair used for `https` resigning.

**Comment by DavideMontersino** [comment]
Thanks!
I just made a pull request (I updated the readme file, plus updated deps)
